In [2]:
import numpy as np

In [3]:
# 1d  array
arrayOne = np.array([1, 2, 3])
type(arrayOne)

numpy.ndarray

In [4]:
# 2d array
arrayTwo = np.array([[1, 2, 3], [4, 5, 6]])
print(arrayTwo.shape)
arrayTwo

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# accessing array
arrayTwo[0][2]

3

In [49]:
zeroArray = np.zeros([2, 4, 3], dtype=np.int64)
zeroArray

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [62]:
eyeArray = np.eye(4, 4, dtype=np.int64)
eyeArray

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int64)

In [50]:
oneArray = np.ones([3, 3, 4, 2], dtype=np.int64)
oneArray

array([[[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]]], dtype=int64)

In [45]:
randArray = np.random.random([3, 4, 5])
randArray

array([[[0.45988512, 0.20894386, 0.66176232, 0.19903498, 0.42124265],
        [0.34937645, 0.56815521, 0.47435896, 0.65877088, 0.47724741],
        [0.37950762, 0.74143191, 0.88974708, 0.74100715, 0.78517049],
        [0.06641628, 0.61554851, 0.01925937, 0.12319373, 0.12434385]],

       [[0.8815415 , 0.47975177, 0.67883862, 0.01844668, 0.63773595],
        [0.17012061, 0.87299893, 0.26866081, 0.57905782, 0.82457724],
        [0.50444015, 0.46949492, 0.16484593, 0.92353382, 0.60669684],
        [0.12456176, 0.54383171, 0.01407726, 0.03645201, 0.22782991]],

       [[0.74583801, 0.12877282, 0.72475293, 0.6563174 , 0.74925587],
        [0.31996315, 0.45507004, 0.41621328, 0.05225029, 0.62089418],
        [0.5623987 , 0.0691487 , 0.81996756, 0.61045709, 0.86203388],
        [0.09534273, 0.74706673, 0.83450032, 0.72800692, 0.47913564]]])

In [47]:
# slicing & indexing 
copyRandArray = randArray[:2 , 0:2, 1:].copy()
randArray[:2 , 0:2, 1:]

array([[[0.20894386, 0.66176232, 0.19903498, 0.42124265],
        [0.56815521, 0.47435896, 0.65877088, 0.47724741]],

       [[0.47975177, 0.67883862, 0.01844668, 0.63773595],
        [0.87299893, 0.26866081, 0.57905782, 0.82457724]]])

In [63]:
for i in copyRandArray:
    for j in i:
        for k in j:
            print(k)

0.20894385519883618
0.6617623179789811
0.19903497810466364
0.42124265095530156
0.568155214549649
0.4743589573309235
0.6587708800567345
0.4772474063137605
0.47975176741365877
0.6788386233129572
0.01844667629863861
0.6377359526065851
0.8729989288744759
0.2686608069863847
0.5790578232003261
0.824577236291022


In [12]:
def addition(x, y):
    print(x+y)
    
listOne = [1, 2, 3, 4, 5]
listTwo = [2, 3, 4, 5, 6]

result = map(addition, listOne, listTwo)

print(type(result))
for i in result:
    print(i)

<class 'map'>
3
None
5
None
7
None
9
None
11
None


In [56]:
# deep copy and shallow copy 
firstArray = np.array([[1, 2, 3], [2, 3, 4]])
firstArray

array([[1, 2, 3],
       [2, 3, 4]])

In [57]:
# deep copy
secondArray = firstArray.copy()
secondArray

array([[1, 2, 3],
       [2, 3, 4]])

In [58]:
firstArray[0, 1] = 3
print(secondArray)
firstArray

[[1 2 3]
 [2 3 4]]


array([[1, 3, 3],
       [2, 3, 4]])

In [59]:
thirdArray = np.copy(firstArray)
thirdArray

array([[1, 3, 3],
       [2, 3, 4]])

In [61]:
firstArray[0, 1] = 2
print(firstArray)
thirdArray

[[1 2 3]
 [2 3 4]]


array([[1, 3, 3],
       [2, 3, 4]])