In [1]:
import numpy as np

In [2]:
# 1d  array
arrayOne = np.array([1, 2, 3])
type(arrayOne)

numpy.ndarray

In [3]:
# 2d array
arrayTwo = np.array([[1, 2, 3], [4, 5, 6]])
print(arrayTwo.shape)
arrayTwo

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# accessing array
arrayTwo[0][2]

3

In [5]:
zeroArray = np.zeros([2, 4, 3], dtype=np.int64)
zeroArray

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [6]:
eyeArray = np.eye(4, 4, dtype=np.int64)
eyeArray

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int64)

In [7]:
oneArray = np.ones([3, 3, 4, 2], dtype=np.int64)
oneArray

array([[[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]]], dtype=int64)

In [8]:
randArray = np.random.random([3, 4, 5])
randArray.shape

(3, 4, 5)

In [9]:
# slicing & indexing 
copyRandArray = randArray[:2 , 0:2, 1:].copy()
randArray[:2 , 0:2, 1:]

array([[[0.77348259, 0.75241479, 0.99741026, 0.94552039],
        [0.89847314, 0.03859401, 0.77014243, 0.65406971]],

       [[0.61385955, 0.63553032, 0.12618803, 0.09890092],
        [0.05128364, 0.42186854, 0.99783816, 0.08710838]]])

In [10]:
for i in copyRandArray:
    for j in i:
        for k in j:
            print(k)

0.7734825944107301
0.7524147946857047
0.9974102579379246
0.9455203878995139
0.8984731380375424
0.03859401453261613
0.7701424333216328
0.6540697128087841
0.6138595478347091
0.6355303198174306
0.12618802671204732
0.09890092099757164
0.0512836425176163
0.4218685429857413
0.9978381603073636
0.08710838352012351


In [11]:
def addition(x, y):
    print(x+y)
    
listOne = [1, 2, 3, 4, 5]
listTwo = [2, 3, 4, 5, 6]

result = map(addition, listOne, listTwo)

print(type(result))
flag = 0

for i in result:
    flag += 1
    print(type(i), i, flag)

<class 'map'>
3
<class 'NoneType'> None 1
5
<class 'NoneType'> None 2
7
<class 'NoneType'> None 3
9
<class 'NoneType'> None 4
11
<class 'NoneType'> None 5


In [12]:
# deep copy and shallow copy 
firstArray = np.array([[1, 2, 3], [2, 3, 4]])
firstArray

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
# deep copy
secondArray = firstArray.copy()
secondArray

array([[1, 2, 3],
       [2, 3, 4]])

In [14]:
firstArray[0, 1] = 3
print(secondArray)
firstArray

[[1 2 3]
 [2 3 4]]


array([[1, 3, 3],
       [2, 3, 4]])

In [15]:
thirdArray = np.copy(firstArray)
thirdArray

array([[1, 3, 3],
       [2, 3, 4]])

In [16]:
firstArray[0, 1] = 2
print(firstArray)
thirdArray

[[1 2 3]
 [2 3 4]]


array([[1, 3, 3],
       [2, 3, 4]])

In [17]:
randInt = np.random.randint(3, 10, size=(3, 3))
randInt

array([[6, 8, 9],
       [7, 4, 8],
       [8, 3, 3]])

## Boolean Indexing

In [18]:
randIntTwo = randInt.copy()
randIntTwo

array([[6, 8, 9],
       [7, 4, 8],
       [8, 3, 3]])

In [19]:
resArray = randIntTwo > 5
resArray

array([[ True,  True,  True],
       [ True, False,  True],
       [ True, False, False]])

In [20]:
randIntThree = np.random.randint(3, 10, size=(3, 3))
randIntThree

array([[8, 8, 5],
       [3, 4, 9],
       [3, 6, 9]])

In [21]:
print(randIntThree)
randIntTwo

[[8 8 5]
 [3 4 9]
 [3 6 9]]


array([[6, 8, 9],
       [7, 4, 8],
       [8, 3, 3]])

In [22]:
print(randIntTwo[resArray])
print(type(resArray))
print(randIntTwo[randIntTwo > randIntThree])
print(randIntThree[randIntTwo > randIntThree])

[6 8 9 7 8 8]
<class 'numpy.ndarray'>
[9 7 8]
[5 3 3]


In [23]:
randIntThree

array([[8, 8, 5],
       [3, 4, 9],
       [3, 6, 9]])

In [24]:
randIntThree[randIntThree % 2 == 0] += 100

In [25]:
randIntThree

array([[108, 108,   5],
       [  3, 104,   9],
       [  3, 106,   9]])

## Datatype And Operators

In [26]:
ex1 = np.array([[1, 2, 3], [2, 3, 4]], dtype=np.int64)
print(ex1.dtype)
ex1.shape

int64


(2, 3)

In [27]:
# force float into integer using floor function
ex2 = np.array(ex1, dtype=np.float32)
print(ex2.shape)
ex2

(2, 3)


array([[1., 2., 3.],
       [2., 3., 4.]], dtype=float32)

## Arithmetic Operations

In [28]:
arr1 = np.random.randint(3, 10, size=(3, 3))
arr2 = np.random.randint(3, 10, size=(3, 3))

arr1, arr2

(array([[7, 3, 4],
        [4, 6, 9],
        [7, 7, 6]]), array([[4, 9, 8],
        [3, 6, 7],
        [3, 8, 5]]))

In [29]:
print(arr1 + arr2) 
print(np.add(arr1, arr2))

[[11 12 12]
 [ 7 12 16]
 [10 15 11]]
[[11 12 12]
 [ 7 12 16]
 [10 15 11]]


In [30]:
print(np.subtract(arr1, arr2, dtype=np.int64))
print('\n','*' * 100, '\n')
print(np.multiply(arr1, arr2, dtype=np.int64))
print('\n','*' * 100, '\n')
print(np.divide(arr1, arr2))
print('\n','*' * 100, '\n')
print(np.sqrt(arr1))
print('\n','*' * 100, '\n')
print(np.exp(arr1))

[[ 3 -6 -4]
 [ 1  0  2]
 [ 4 -1  1]]

 **************************************************************************************************** 

[[28 27 32]
 [12 36 63]
 [21 56 30]]

 **************************************************************************************************** 

[[1.75       0.33333333 0.5       ]
 [1.33333333 1.         1.28571429]
 [2.33333333 0.875      1.2       ]]

 **************************************************************************************************** 

[[2.64575131 1.73205081 2.        ]
 [2.         2.44948974 3.        ]
 [2.64575131 2.64575131 2.44948974]]

 **************************************************************************************************** 

[[1096.63315843   20.08553692   54.59815003]
 [  54.59815003  403.42879349 8103.08392758]
 [1096.63315843 1096.63315843  403.42879349]]


## Statistical Operations

In [65]:
arrayOne = np.random.randint(0, 10, size=(3, 3))
arrayOne

array([[7, 7, 4],
       [9, 3, 2],
       [0, 3, 1]])

In [66]:
print(arrayOne.mean())

4.0


In [67]:
arrayOne.mean(axis=1)

array([6.        , 4.66666667, 1.33333333])

In [68]:
arrayOne.mean(axis=0)

array([5.33333333, 4.33333333, 2.33333333])

In [69]:
arrayOne.sum()

36

In [70]:
print(arrayOne)
arrayOne.sum(axis=1)

[[7 7 4]
 [9 3 2]
 [0 3 1]]


array([18, 14,  4])

In [36]:
print(arrayOne)
np.median(arrayOne, axis=0)

[[4 2 5]
 [4 1 9]
 [4 3 9]]


array([4., 2., 9.])

In [37]:
np.median(arrayOne, axis=1)

array([4., 4., 4.])

In [38]:
#Sorting
print(arrayOne)
arrayTwo = arrayOne.copy()
print(arrayTwo)
arrayTwo.sort(axis=0)
arrayTwo

[[4 2 5]
 [4 1 9]
 [4 3 9]]
[[4 2 5]
 [4 1 9]
 [4 3 9]]


array([[4, 1, 5],
       [4, 2, 9],
       [4, 3, 9]])

In [39]:
# Find Unique Elements
print(arrayOne)
print(arrayTwo)
np.unique(arrayOne, axis=0)

[[4 2 5]
 [4 1 9]
 [4 3 9]]
[[4 1 5]
 [4 2 9]
 [4 3 9]]


array([[4, 1, 9],
       [4, 2, 5],
       [4, 3, 9]])

In [40]:
arrayOne = np.random.randint(0, 10, size=(4, 4))
arrayOne

array([[5, 9, 6, 7],
       [5, 1, 8, 0],
       [2, 7, 8, 1],
       [5, 8, 7, 0]])

In [41]:
arrayOne.reshape(2, 8)

array([[5, 9, 6, 7, 5, 1, 8, 0],
       [2, 7, 8, 1, 5, 8, 7, 0]])

In [42]:
np.arange(9, 16, 3)

array([ 9, 12, 15])

In [73]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [44]:
print("Hello World!")

Hello World!


In [45]:
arrayOne = np.random.randint(0, 10, size=(1, 3)) 
print(np.median(arrayOne))
arrayOne

3.0


array([[8, 2, 3]])

In [46]:
randArray = np.random.randint(0, 100, size=(4, 4))
print(randArray)

filterArray = randArray > 20
print(filterArray)

resArray = randArray[filterArray]
print(resArray)

resArray[resArray % 2 == 0] += 100
resArray

[[ 6  6 30 47]
 [27  3 44 85]
 [50 89  7 53]
 [45 84 81 86]]
[[False False  True  True]
 [ True False  True  True]
 [ True  True False  True]
 [ True  True  True  True]]
[30 47 27 44 85 50 89 53 45 84 81 86]


array([130,  47,  27, 144,  85, 150,  89,  53,  45, 184,  81, 186])

In [47]:
randOne = np.random.randint(0, 10, size=(2, 2))
randTwo = np.random.randint(0, 10, size=(2, 2))

In [48]:
print(randOne, "\n\n\n", randTwo)

[[1 9]
 [9 3]] 


 [[6 0]
 [6 4]]


In [49]:
np.intersect1d(randOne, randTwo)

array([], dtype=int32)

In [50]:
np.union1d(randOne, randTwo)

array([0, 1, 3, 4, 6, 9])

## Brodcasting

In [51]:
randOne = np.random.randint(0, 10, size=(3, 3))
randOne

array([[2, 4, 8],
       [5, 1, 4],
       [9, 4, 1]])

In [52]:
randTwo = np.random.randint(0, 10, size=(1, 3))
randTwo

array([[5, 2, 6]])

In [53]:
randOne + randTwo

array([[ 7,  6, 14],
       [10,  3, 10],
       [14,  6,  7]])

In [54]:
randOne + randTwo.T

array([[ 7,  9, 13],
       [ 7,  3,  6],
       [15, 10,  7]])

In [55]:
randArray = np.random.randint(0, 2, size=(1, 10))
randArray

array([[1, 1, 0, 0, 1, 0, 0, 0, 0, 1]])

In [56]:
arrayOne = np.random.randint(0, 100, size=(1, 10))
arrayTwo = np.random.randint(0, 100, size=(1, 10))
print(arrayOne, arrayTwo)

[[74 17 34  8 14 50 38 16 21 21]] [[ 7 84 83  5 41 38 13 13 68 90]]


In [57]:
resArray = np.where(randArray, arrayOne, arrayTwo)

In [58]:
resArray

array([[74, 17, 83,  5, 14, 38, 13, 13, 68, 21]])

In [77]:
np.all(resArray)

True

In [59]:
randArray.any()

True

In [60]:
randArray.all()

False

In [61]:
randArrayTwo = np.random.randint(1, 2, size=(1, 10))
randArrayTwo

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [62]:
randArrayTwo.all()

True

In [63]:
import copy
num = 12
num2 = copy.deepcopy(num)
num2

12