In [2]:
import numpy as np

In [3]:
# 1d  array
arrayOne = np.array([1, 2, 3])
type(arrayOne)

numpy.ndarray

In [4]:
# 2d array
arrayTwo = np.array([[1, 2, 3], [4, 5, 6]])
print(arrayTwo.shape)
arrayTwo

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# accessing array
arrayTwo[0][2]

3

In [6]:
zeroArray = np.zeros([2, 4, 3], dtype=np.int64)
zeroArray

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [7]:
eyeArray = np.eye(4, 4, dtype=np.int64)
eyeArray

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int64)

In [8]:
oneArray = np.ones([3, 3, 4, 2], dtype=np.int64)
oneArray

array([[[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]]], dtype=int64)

In [9]:
randArray = np.random.random([3, 4, 5])
randArray.shape

(3, 4, 5)

In [10]:
# slicing & indexing 
copyRandArray = randArray[:2 , 0:2, 1:].copy()
randArray[:2 , 0:2, 1:]

array([[[0.57826859, 0.90185309, 0.41961182, 0.75906543],
        [0.6336709 , 0.36885061, 0.63255471, 0.85049644]],

       [[0.47278413, 0.72464505, 0.27367628, 0.38386305],
        [0.04532597, 0.4856967 , 0.09126676, 0.39074746]]])

In [11]:
for i in copyRandArray:
    for j in i:
        for k in j:
            print(k)

0.5782685929327622
0.9018530939362507
0.41961182282582865
0.7590654274338193
0.6336708965449283
0.3688506140559844
0.6325547075257452
0.8504964430519852
0.4727841308116756
0.7246450469136059
0.273676279615521
0.38386304683727746
0.045325967735555195
0.48569670051844516
0.09126676445719573
0.39074745551303103


In [12]:
def addition(x, y):
    print(x+y)
    
listOne = [1, 2, 3, 4, 5]
listTwo = [2, 3, 4, 5, 6]

result = map(addition, listOne, listTwo)

print(type(result))
for i in result:
    print(i)

<class 'map'>
3
None
5
None
7
None
9
None
11
None


In [13]:
# deep copy and shallow copy 
firstArray = np.array([[1, 2, 3], [2, 3, 4]])
firstArray

array([[1, 2, 3],
       [2, 3, 4]])

In [14]:
# deep copy
secondArray = firstArray.copy()
secondArray

array([[1, 2, 3],
       [2, 3, 4]])

In [15]:
firstArray[0, 1] = 3
print(secondArray)
firstArray

[[1 2 3]
 [2 3 4]]


array([[1, 3, 3],
       [2, 3, 4]])

In [16]:
thirdArray = np.copy(firstArray)
thirdArray

array([[1, 3, 3],
       [2, 3, 4]])

In [17]:
firstArray[0, 1] = 2
print(firstArray)
thirdArray

[[1 2 3]
 [2 3 4]]


array([[1, 3, 3],
       [2, 3, 4]])

In [18]:
randInt = np.random.randint(3, 10, size=(3, 3))
randInt

array([[4, 4, 9],
       [6, 7, 7],
       [3, 5, 8]])

## Boolean Indexing

In [19]:
randIntTwo = randInt.copy()
randIntTwo

array([[4, 4, 9],
       [6, 7, 7],
       [3, 5, 8]])

In [20]:
resArray = randIntTwo > 5
resArray

array([[False, False,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [21]:
randIntThree = np.random.randint(3, 10, size=(3, 3))
randIntThree

array([[4, 7, 7],
       [6, 8, 3],
       [7, 6, 5]])

In [22]:
print(randIntThree)
randIntTwo

[[4 7 7]
 [6 8 3]
 [7 6 5]]


array([[4, 4, 9],
       [6, 7, 7],
       [3, 5, 8]])

In [23]:
print(randIntTwo[resArray])
print(type(resArray))
print(randIntTwo[randIntTwo > randIntThree])
print(randIntThree[randIntTwo > randIntThree])

[9 6 7 7 8]
<class 'numpy.ndarray'>
[9 7 8]
[7 3 5]


In [24]:
randIntThree

array([[4, 7, 7],
       [6, 8, 3],
       [7, 6, 5]])

In [25]:
randIntThree[randIntThree % 2 == 0] += 100

In [26]:
randIntThree

array([[104,   7,   7],
       [106, 108,   3],
       [  7, 106,   5]])

## Datatype And Operators

In [28]:
ex1 = np.array([[1, 2, 3], [2, 3, 4]], dtype=np.int64)
print(ex1.dtype)
ex1.shape

int64


(2, 3)

In [32]:
# force float into integer using floor function
ex2 = np.array(ex1, dtype=np.float32)
print(ex2.shape)
ex2

(2, 3)


array([[1., 2., 3.],
       [2., 3., 4.]], dtype=float32)

## Arithmetic Operations

In [38]:
arr1 = np.random.randint(3, 10, size=(3, 3))
arr2 = np.random.randint(3, 10, size=(3, 3))

arr1, arr2

(array([[7, 4, 8],
        [4, 9, 5],
        [9, 6, 9]]), array([[9, 9, 6],
        [4, 3, 4],
        [8, 9, 7]]))

In [39]:
print(arr1 + arr2) 

[[16 13 14]
 [ 8 12  9]
 [17 15 16]]
