In [1]:
import numpy as np

In [2]:
# 1d  array
arrayOne = np.array([1, 2, 3])
type(arrayOne)

numpy.ndarray

In [3]:
# 2d array
arrayTwo = np.array([[1, 2, 3], [4, 5, 6]])
print(arrayTwo.shape)
arrayTwo

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# accessing array
arrayTwo[0][2]

3

In [5]:
zeroArray = np.zeros([2, 4, 3], dtype=np.int64)
zeroArray

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [6]:
eyeArray = np.eye(4, 4, dtype=np.int64)
eyeArray

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int64)

In [7]:
oneArray = np.ones([3, 3, 4, 2], dtype=np.int64)
oneArray

array([[[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]]], dtype=int64)

In [8]:
randArray = np.random.random([3, 4, 5])
randArray.shape

(3, 4, 5)

In [9]:
# slicing & indexing 
copyRandArray = randArray[:2 , 0:2, 1:].copy()
randArray[:2 , 0:2, 1:]

array([[[0.83545798, 0.1757425 , 0.1652747 , 0.72119808],
        [0.1267208 , 0.06241828, 0.54219699, 0.47019027]],

       [[0.27679572, 0.84898109, 0.65264595, 0.778721  ],
        [0.2606865 , 0.37756216, 0.04832683, 0.37932132]]])

In [10]:
for i in copyRandArray:
    for j in i:
        for k in j:
            print(k)

0.8354579814507685
0.17574250224617327
0.16527470226086238
0.72119808397462
0.12672079834385874
0.06241828104802771
0.542196994964465
0.47019026581647405
0.2767957202168726
0.8489810921797594
0.6526459524587049
0.7787210020514809
0.2606864950124246
0.37756216016140287
0.04832682982037839
0.37932131998309593


In [11]:
def addition(x, y):
    print(x+y)
    
listOne = [1, 2, 3, 4, 5]
listTwo = [2, 3, 4, 5, 6]

result = map(addition, listOne, listTwo)

print(type(result))
for i in result:
    print(i)

<class 'map'>
3
None
5
None
7
None
9
None
11
None


In [12]:
# deep copy and shallow copy 
firstArray = np.array([[1, 2, 3], [2, 3, 4]])
firstArray

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
# deep copy
secondArray = firstArray.copy()
secondArray

array([[1, 2, 3],
       [2, 3, 4]])

In [14]:
firstArray[0, 1] = 3
print(secondArray)
firstArray

[[1 2 3]
 [2 3 4]]


array([[1, 3, 3],
       [2, 3, 4]])

In [15]:
thirdArray = np.copy(firstArray)
thirdArray

array([[1, 3, 3],
       [2, 3, 4]])

In [16]:
firstArray[0, 1] = 2
print(firstArray)
thirdArray

[[1 2 3]
 [2 3 4]]


array([[1, 3, 3],
       [2, 3, 4]])

In [17]:
randInt = np.random.randint(3, 10, size=(3, 3))
randInt

array([[6, 9, 5],
       [9, 8, 6],
       [8, 9, 9]])

## Boolean Indexing

In [18]:
randIntTwo = randInt.copy()
randIntTwo

array([[6, 9, 5],
       [9, 8, 6],
       [8, 9, 9]])

In [19]:
resArray = randIntTwo > 5
resArray

array([[ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [20]:
randIntThree = np.random.randint(3, 10, size=(3, 3))
randIntThree

array([[5, 9, 9],
       [8, 9, 6],
       [5, 9, 6]])

In [21]:
print(randIntThree)
randIntTwo

[[5 9 9]
 [8 9 6]
 [5 9 6]]


array([[6, 9, 5],
       [9, 8, 6],
       [8, 9, 9]])

In [22]:
print(randIntTwo[resArray])
print(type(resArray))
print(randIntTwo[randIntTwo > randIntThree])
print(randIntThree[randIntTwo > randIntThree])

[6 9 9 8 6 8 9 9]
<class 'numpy.ndarray'>
[6 9 8 9]
[5 8 5 6]


In [23]:
randIntThree

array([[5, 9, 9],
       [8, 9, 6],
       [5, 9, 6]])

In [24]:
randIntThree[randIntThree % 2 == 0] += 100

In [25]:
randIntThree

array([[  5,   9,   9],
       [108,   9, 106],
       [  5,   9, 106]])

## Datatype And Operators

In [26]:
ex1 = np.array([[1, 2, 3], [2, 3, 4]], dtype=np.int64)
print(ex1.dtype)
ex1.shape

int64


(2, 3)

In [27]:
# force float into integer using floor function
ex2 = np.array(ex1, dtype=np.float32)
print(ex2.shape)
ex2

(2, 3)


array([[1., 2., 3.],
       [2., 3., 4.]], dtype=float32)

## Arithmetic Operations

In [28]:
arr1 = np.random.randint(3, 10, size=(3, 3))
arr2 = np.random.randint(3, 10, size=(3, 3))

arr1, arr2

(array([[4, 5, 6],
        [4, 5, 4],
        [8, 9, 3]]), array([[8, 8, 8],
        [5, 8, 3],
        [4, 3, 8]]))

In [29]:
print(arr1 + arr2) 
print(np.add(arr1, arr2))

[[12 13 14]
 [ 9 13  7]
 [12 12 11]]
[[12 13 14]
 [ 9 13  7]
 [12 12 11]]


In [40]:
print(np.subtract(arr1, arr2, dtype=np.int64))
print('\n','*' * 100, '\n')
print(np.multiply(arr1, arr2, dtype=np.int64))
print('\n','*' * 100, '\n')
print(np.divide(arr1, arr2))
print('\n','*' * 100, '\n')
print(np.sqrt(arr1))
print('\n','*' * 100, '\n')
print(np.exp(arr1))

[[-4 -3 -2]
 [-1 -3  1]
 [ 4  6 -5]]

 **************************************************************************************************** 

[[32 40 48]
 [20 40 12]
 [32 27 24]]

 **************************************************************************************************** 

[[0.5        0.625      0.75      ]
 [0.8        0.625      1.33333333]
 [2.         3.         0.375     ]]

 **************************************************************************************************** 

[[2.         2.23606798 2.44948974]
 [2.         2.23606798 2.        ]
 [2.82842712 3.         1.73205081]]

 **************************************************************************************************** 

[[  54.59815003  148.4131591   403.42879349]
 [  54.59815003  148.4131591    54.59815003]
 [2980.95798704 8103.08392758   20.08553692]]


## Statistical Operations

In [45]:
arrayOne = np.random.randint(0, 10, size=(3, 3))
arrayOne

array([[0, 6, 6],
       [0, 6, 2],
       [9, 6, 6]])

In [46]:
print(arrayOne.mean())

4.555555555555555


In [53]:
arrayOne.mean(axis=1)

array([4.        , 2.66666667, 7.        ])

In [54]:
arrayOne.mean(axis=0)

array([3.        , 6.        , 4.66666667])

In [55]:
arrayOne.sum()

41

In [58]:
print(arrayOne)
np.median(arrayOne, axis=0)

[[0 6 6]
 [0 6 2]
 [9 6 6]]


array([0., 6., 6.])

In [60]:
np.median(arrayOne, axis=1)

array([6., 2., 6.])

In [68]:
#Sorting
print(arrayOne)
arrayTwo = arrayOne.copy()
print(arrayTwo)
arrayTwo.sort(axis=0)
arrayTwo

[[0 6 6]
 [0 6 2]
 [9 6 6]]
[[0 6 6]
 [0 6 2]
 [9 6 6]]


array([[0, 6, 2],
       [0, 6, 6],
       [9, 6, 6]])

In [72]:
# Find Unique Elements
print(arrayOne)
print(arrayTwo)
np.unique(arrayOne, axis=0)

[[0 6 6]
 [0 6 2]
 [9 6 6]]
[[0 6 2]
 [0 6 6]
 [9 6 6]]


array([[0, 6, 2],
       [0, 6, 6],
       [9, 6, 6]])