In [11]:
import numpy as np

In [12]:
# 1d  array
arrayOne = np.array([1, 2, 3])
type(arrayOne)

numpy.ndarray

In [13]:
# 2d array
arrayTwo = np.array([[1, 2, 3], [4, 5, 6]])
print(arrayTwo.shape)
arrayTwo

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# accessing array
arrayTwo[0][2]

3

In [15]:
zeroArray = np.zeros([2, 4, 3], dtype=np.int64)
zeroArray

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [16]:
eyeArray = np.eye(4, 4, dtype=np.int64)
eyeArray

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int64)

In [17]:
oneArray = np.ones([3, 3, 4, 2], dtype=np.int64)
oneArray

array([[[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]]], dtype=int64)

In [18]:
randArray = np.random.random([3, 4, 5])
randArray.shape

(3, 4, 5)

In [19]:
# slicing & indexing 
copyRandArray = randArray[:2 , 0:2, 1:].copy()
randArray[:2 , 0:2, 1:]

array([[[8.81159322e-01, 7.06847178e-01, 8.09133778e-01, 2.01256345e-01],
        [9.46892923e-01, 2.42228055e-01, 8.69919821e-04, 9.34637795e-01]],

       [[2.93358583e-01, 6.22569016e-01, 5.12396853e-01, 4.31106792e-01],
        [2.61418885e-01, 6.68178490e-02, 7.83230145e-01, 9.48304524e-01]]])

In [20]:
for i in copyRandArray:
    for j in i:
        for k in j:
            print(k)

0.8811593216049338
0.7068471780128026
0.8091337784899236
0.20125634464549091
0.9468929230511685
0.24222805519546897
0.0008699198211272741
0.934637794930982
0.29335858256267555
0.6225690155699359
0.5123968527376825
0.43110679234286375
0.2614188845046521
0.06681784897466814
0.7832301449395942
0.9483045243695524


In [21]:
def addition(x, y):
    print(x+y)
    
listOne = [1, 2, 3, 4, 5]
listTwo = [2, 3, 4, 5, 6]

result = map(addition, listOne, listTwo)

print(type(result))
for i in result:
    print(i)

<class 'map'>
3
None
5
None
7
None
9
None
11
None


In [22]:
# deep copy and shallow copy 
firstArray = np.array([[1, 2, 3], [2, 3, 4]])
firstArray

array([[1, 2, 3],
       [2, 3, 4]])

In [23]:
# deep copy
secondArray = firstArray.copy()
secondArray

array([[1, 2, 3],
       [2, 3, 4]])

In [24]:
firstArray[0, 1] = 3
print(secondArray)
firstArray

[[1 2 3]
 [2 3 4]]


array([[1, 3, 3],
       [2, 3, 4]])

In [25]:
thirdArray = np.copy(firstArray)
thirdArray

array([[1, 3, 3],
       [2, 3, 4]])

In [28]:
firstArray[0, 1] = 2
print(firstArray)
thirdArray

[[1 2 3]
 [2 3 4]]


array([[1, 3, 3],
       [2, 3, 4]])

In [38]:
randInt = np.random.randint(3, 10, size=(3, 3))
randInt

array([[7, 9, 5],
       [7, 6, 5],
       [4, 4, 9]])

## Boolean Indexing

In [40]:
randIntTwo = randInt.copy()
randIntTwo

array([[7, 9, 5],
       [7, 6, 5],
       [4, 4, 9]])

In [42]:
resArray = randIntTwo > 5
resArray

array([[ True,  True, False],
       [ True,  True, False],
       [False, False,  True]])

In [48]:
randIntThree = np.random.randint(3, 10, size=(3, 3))
randIntThree

array([[9, 4, 7],
       [7, 9, 6],
       [3, 4, 8]])

In [53]:
print(randIntThree)
randIntTwo

[[9 4 7]
 [7 9 6]
 [3 4 8]]


array([[7, 9, 5],
       [7, 6, 5],
       [4, 4, 9]])

In [52]:
print(randIntTwo[resArray])
print(type(resArray))
print(randIntTwo[randIntTwo > randIntThree])
print(randIntThree[randIntTwo > randIntThree])

[7 9 7 6 9]
<class 'numpy.ndarray'>
[9 4 9]
[4 3 8]
