In [1]:
import numpy as np

In [2]:
# 1d  array
arrayOne = np.array([1, 2, 3])
type(arrayOne)

numpy.ndarray

In [3]:
# 2d array
arrayTwo = np.array([[1, 2, 3], [4, 5, 6]])
print(arrayTwo.shape)
arrayTwo

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# accessing array
arrayTwo[0][2]

3

In [5]:
zeroArray = np.zeros([2, 4, 3], dtype=np.int64)
zeroArray

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [6]:
eyeArray = np.eye(4, 4, dtype=np.int64)
eyeArray

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int64)

In [7]:
oneArray = np.ones([3, 3, 4, 2], dtype=np.int64)
oneArray

array([[[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]]], dtype=int64)

In [8]:
randArray = np.random.random([3, 4, 5])
randArray.shape

(3, 4, 5)

In [9]:
# slicing & indexing 
copyRandArray = randArray[:2 , 0:2, 1:].copy()
randArray[:2 , 0:2, 1:]

array([[[0.99649159, 0.38798216, 0.21902873, 0.88718761],
        [0.15302117, 0.29483384, 0.05596944, 0.1972346 ]],

       [[0.68103288, 0.88531718, 0.72223158, 0.24067189],
        [0.06163101, 0.23994218, 0.00983273, 0.16769296]]])

In [10]:
for i in copyRandArray:
    for j in i:
        for k in j:
            print(k)

0.9964915892307606
0.38798215867799923
0.2190287348765434
0.8871876116807179
0.15302116639358587
0.2948338427144389
0.05596944133788018
0.19723460252973923
0.6810328756280842
0.88531718494932
0.7222315772091542
0.24067188651800142
0.06163100594087256
0.23994218286072067
0.009832732924263454
0.16769296021707747


In [11]:
def addition(x, y):
    print(x+y)
    
listOne = [1, 2, 3, 4, 5]
listTwo = [2, 3, 4, 5, 6]

result = map(addition, listOne, listTwo)

print(type(result))
for i in result:
    print(i)

<class 'map'>
3
None
5
None
7
None
9
None
11
None


In [12]:
# deep copy and shallow copy 
firstArray = np.array([[1, 2, 3], [2, 3, 4]])
firstArray

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
# deep copy
secondArray = firstArray.copy()
secondArray

array([[1, 2, 3],
       [2, 3, 4]])

In [14]:
firstArray[0, 1] = 3
print(secondArray)
firstArray

[[1 2 3]
 [2 3 4]]


array([[1, 3, 3],
       [2, 3, 4]])

In [15]:
thirdArray = np.copy(firstArray)
thirdArray

array([[1, 3, 3],
       [2, 3, 4]])

In [16]:
firstArray[0, 1] = 2
print(firstArray)
thirdArray

[[1 2 3]
 [2 3 4]]


array([[1, 3, 3],
       [2, 3, 4]])

In [17]:
randInt = np.random.randint(3, 10, size=(3, 3))
randInt

array([[7, 5, 9],
       [6, 7, 7],
       [8, 8, 9]])

## Boolean Indexing

In [18]:
randIntTwo = randInt.copy()
randIntTwo

array([[7, 5, 9],
       [6, 7, 7],
       [8, 8, 9]])

In [19]:
resArray = randIntTwo > 5
resArray

array([[ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [20]:
randIntThree = np.random.randint(3, 10, size=(3, 3))
randIntThree

array([[9, 9, 7],
       [9, 6, 4],
       [9, 4, 6]])

In [21]:
print(randIntThree)
randIntTwo

[[9 9 7]
 [9 6 4]
 [9 4 6]]


array([[7, 5, 9],
       [6, 7, 7],
       [8, 8, 9]])

In [22]:
print(randIntTwo[resArray])
print(type(resArray))
print(randIntTwo[randIntTwo > randIntThree])
print(randIntThree[randIntTwo > randIntThree])

[7 9 6 7 7 8 8 9]
<class 'numpy.ndarray'>
[9 7 7 8 9]
[7 6 4 4 6]


In [23]:
randIntThree

array([[9, 9, 7],
       [9, 6, 4],
       [9, 4, 6]])

In [24]:
randIntThree[randIntThree % 2 == 0] += 100

In [25]:
randIntThree

array([[  9,   9,   7],
       [  9, 106, 104],
       [  9, 104, 106]])

## Datatype And Operators

In [26]:
ex1 = np.array([[1, 2, 3], [2, 3, 4]], dtype=np.int64)
print(ex1.dtype)
ex1.shape

int64


(2, 3)

In [27]:
# force float into integer using floor function
ex2 = np.array(ex1, dtype=np.float32)
print(ex2.shape)
ex2

(2, 3)


array([[1., 2., 3.],
       [2., 3., 4.]], dtype=float32)

## Arithmetic Operations

In [28]:
arr1 = np.random.randint(3, 10, size=(3, 3))
arr2 = np.random.randint(3, 10, size=(3, 3))

arr1, arr2

(array([[8, 9, 6],
        [6, 4, 5],
        [9, 9, 8]]), array([[6, 9, 3],
        [9, 3, 6],
        [8, 6, 8]]))

In [29]:
print(arr1 + arr2) 
print(np.add(arr1, arr2))

[[14 18  9]
 [15  7 11]
 [17 15 16]]
[[14 18  9]
 [15  7 11]
 [17 15 16]]


In [30]:
print(np.subtract(arr1, arr2, dtype=np.int64))
print('\n','*' * 100, '\n')
print(np.multiply(arr1, arr2, dtype=np.int64))
print('\n','*' * 100, '\n')
print(np.divide(arr1, arr2))
print('\n','*' * 100, '\n')
print(np.sqrt(arr1))
print('\n','*' * 100, '\n')
print(np.exp(arr1))

[[ 2  0  3]
 [-3  1 -1]
 [ 1  3  0]]

 **************************************************************************************************** 

[[48 81 18]
 [54 12 30]
 [72 54 64]]

 **************************************************************************************************** 

[[1.33333333 1.         2.        ]
 [0.66666667 1.33333333 0.83333333]
 [1.125      1.5        1.        ]]

 **************************************************************************************************** 

[[2.82842712 3.         2.44948974]
 [2.44948974 2.         2.23606798]
 [3.         3.         2.82842712]]

 **************************************************************************************************** 

[[2980.95798704 8103.08392758  403.42879349]
 [ 403.42879349   54.59815003  148.4131591 ]
 [8103.08392758 8103.08392758 2980.95798704]]


## Statistical Operations

In [31]:
arrayOne = np.random.randint(0, 10, size=(3, 3))
arrayOne

array([[7, 1, 3],
       [1, 9, 6],
       [8, 0, 9]])

In [32]:
print(arrayOne.mean())

4.888888888888889


In [33]:
arrayOne.mean(axis=1)

array([3.66666667, 5.33333333, 5.66666667])

In [34]:
arrayOne.mean(axis=0)

array([5.33333333, 3.33333333, 6.        ])

In [35]:
arrayOne.sum()

44

In [36]:
print(arrayOne)
np.median(arrayOne, axis=0)

[[7 1 3]
 [1 9 6]
 [8 0 9]]


array([7., 1., 6.])

In [37]:
np.median(arrayOne, axis=1)

array([3., 6., 8.])

In [38]:
#Sorting
print(arrayOne)
arrayTwo = arrayOne.copy()
print(arrayTwo)
arrayTwo.sort(axis=0)
arrayTwo

[[7 1 3]
 [1 9 6]
 [8 0 9]]
[[7 1 3]
 [1 9 6]
 [8 0 9]]


array([[1, 0, 3],
       [7, 1, 6],
       [8, 9, 9]])

In [39]:
# Find Unique Elements
print(arrayOne)
print(arrayTwo)
np.unique(arrayOne, axis=0)

[[7 1 3]
 [1 9 6]
 [8 0 9]]
[[1 0 3]
 [7 1 6]
 [8 9 9]]


array([[1, 9, 6],
       [7, 1, 3],
       [8, 0, 9]])

In [40]:
arrayOne = np.random.randint(0, 10, size=(4, 4))
arrayOne

array([[4, 5, 2, 6],
       [8, 3, 4, 7],
       [2, 4, 6, 9],
       [6, 8, 7, 4]])

In [41]:
arrayOne.reshape(2, 8)

array([[4, 5, 2, 6, 8, 3, 4, 7],
       [2, 4, 6, 9, 6, 8, 7, 4]])

In [42]:
np.arange(9, 16, 3)

array([ 9, 12, 15])

In [43]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [44]:
print("Hello World!")

Hello World!


In [52]:
arrayOne = np.random.randint(0, 10, size=(1, 3)) 
print(np.median(arrayOne))
arrayOne

6.0


array([[6, 5, 6]])

In [58]:
randArray = np.random.randint(0, 100, size=(4, 4))
print(randArray)

filterArray = randArray > 20
print(filterArray)

resArray = randArray[filterArray]
print(resArray)

resArray[resArray % 2 == 0] += 100
resArray

[[59 33 35 69]
 [48  8 55 81]
 [19 32 75 79]
 [39 79 71 49]]
[[ True  True  True  True]
 [ True False  True  True]
 [False  True  True  True]
 [ True  True  True  True]]
[59 33 35 69 48 55 81 32 75 79 39 79 71 49]


array([ 59,  33,  35,  69, 148,  55,  81, 132,  75,  79,  39,  79,  71,
        49])

In [73]:
randOne = np.random.randint(0, 10, size=(2, 2))
randTwo = np.random.randint(0, 10, size=(2, 2))

In [74]:
print(randOne, "\n\n\n", randTwo)

[[5 3]
 [6 5]] 


 [[4 3]
 [5 2]]


In [75]:
np.intersect1d(randOne, randTwo)

array([3, 5])

In [76]:
np.union1d(randOne, randTwo)

array([2, 3, 4, 5, 6])

## Brodcasting

In [78]:
randOne = np.random.randint(0, 10, size=(3, 3))
randOne

array([[3, 8, 6],
       [2, 6, 4],
       [8, 4, 7]])

In [80]:
randTwo = np.random.randint(0, 10, size=(1, 3))
randTwo

array([[1, 1, 6]])

In [81]:
randOne + randTwo

array([[ 4,  9, 12],
       [ 3,  7, 10],
       [ 9,  5, 13]])

In [83]:
randOne + randTwo.T

array([[ 4,  9,  7],
       [ 3,  7,  5],
       [14, 10, 13]])