In [1]:
import numpy as np

In [2]:
# 1d  array
arrayOne = np.array([1, 2, 3])
type(arrayOne)

numpy.ndarray

In [3]:
# 2d array
arrayTwo = np.array([[1, 2, 3], [4, 5, 6]])
print(arrayTwo.shape)
arrayTwo

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# accessing array
arrayTwo[0][2]

3

In [5]:
zeroArray = np.zeros([2, 4, 3], dtype=np.int64)
zeroArray

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [6]:
eyeArray = np.eye(4, 4, dtype=np.int64)
eyeArray

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int64)

In [7]:
oneArray = np.ones([3, 3, 4, 2], dtype=np.int64)
oneArray

array([[[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]]], dtype=int64)

In [8]:
randArray = np.random.random([3, 4, 5])
randArray.shape

(3, 4, 5)

In [9]:
# slicing & indexing 
copyRandArray = randArray[:2 , 0:2, 1:].copy()
randArray[:2 , 0:2, 1:]

array([[[0.36889451, 0.0289855 , 0.58555714, 0.94373825],
        [0.52904438, 0.95334493, 0.58247942, 0.25321361]],

       [[0.85897065, 0.77350927, 0.82312766, 0.36669702],
        [0.86614318, 0.45504775, 0.87176965, 0.15827341]]])

In [10]:
for i in copyRandArray:
    for j in i:
        for k in j:
            print(k)

0.3688945132355157
0.02898549658458549
0.5855571449659537
0.943738252371254
0.5290443829803528
0.9533449311872256
0.5824794228277432
0.25321360580594554
0.8589706512483276
0.7735092714211358
0.8231276585362068
0.3666970188914126
0.8661431785719174
0.4550477492371533
0.8717696496039248
0.15827341053009547


In [11]:
def addition(x, y):
    print(x+y)
    
listOne = [1, 2, 3, 4, 5]
listTwo = [2, 3, 4, 5, 6]

result = map(addition, listOne, listTwo)

print(type(result))
for i in result:
    print(i)

<class 'map'>
3
None
5
None
7
None
9
None
11
None


In [12]:
# deep copy and shallow copy 
firstArray = np.array([[1, 2, 3], [2, 3, 4]])
firstArray

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
# deep copy
secondArray = firstArray.copy()
secondArray

array([[1, 2, 3],
       [2, 3, 4]])

In [14]:
firstArray[0, 1] = 3
print(secondArray)
firstArray

[[1 2 3]
 [2 3 4]]


array([[1, 3, 3],
       [2, 3, 4]])

In [15]:
thirdArray = np.copy(firstArray)
thirdArray

array([[1, 3, 3],
       [2, 3, 4]])

In [16]:
firstArray[0, 1] = 2
print(firstArray)
thirdArray

[[1 2 3]
 [2 3 4]]


array([[1, 3, 3],
       [2, 3, 4]])

In [17]:
randInt = np.random.randint(3, 10, size=(3, 3))
randInt

array([[7, 8, 4],
       [9, 7, 8],
       [8, 3, 3]])

## Boolean Indexing

In [18]:
randIntTwo = randInt.copy()
randIntTwo

array([[7, 8, 4],
       [9, 7, 8],
       [8, 3, 3]])

In [19]:
resArray = randIntTwo > 5
resArray

array([[ True,  True, False],
       [ True,  True,  True],
       [ True, False, False]])

In [20]:
randIntThree = np.random.randint(3, 10, size=(3, 3))
randIntThree

array([[5, 8, 4],
       [8, 5, 3],
       [3, 3, 7]])

In [21]:
print(randIntThree)
randIntTwo

[[5 8 4]
 [8 5 3]
 [3 3 7]]


array([[7, 8, 4],
       [9, 7, 8],
       [8, 3, 3]])

In [22]:
print(randIntTwo[resArray])
print(type(resArray))
print(randIntTwo[randIntTwo > randIntThree])
print(randIntThree[randIntTwo > randIntThree])

[7 8 9 7 8 8]
<class 'numpy.ndarray'>
[7 9 7 8 8]
[5 8 5 3 3]


In [23]:
randIntThree

array([[5, 8, 4],
       [8, 5, 3],
       [3, 3, 7]])

In [24]:
randIntThree[randIntThree % 2 == 0] += 100

In [25]:
randIntThree

array([[  5, 108, 104],
       [108,   5,   3],
       [  3,   3,   7]])

## Datatype And Operators

In [26]:
ex1 = np.array([[1, 2, 3], [2, 3, 4]], dtype=np.int64)
print(ex1.dtype)
ex1.shape

int64


(2, 3)

In [27]:
# force float into integer using floor function
ex2 = np.array(ex1, dtype=np.float32)
print(ex2.shape)
ex2

(2, 3)


array([[1., 2., 3.],
       [2., 3., 4.]], dtype=float32)

## Arithmetic Operations

In [28]:
arr1 = np.random.randint(3, 10, size=(3, 3))
arr2 = np.random.randint(3, 10, size=(3, 3))

arr1, arr2

(array([[9, 3, 6],
        [7, 3, 7],
        [8, 4, 4]]), array([[6, 7, 5],
        [5, 6, 5],
        [6, 7, 3]]))

In [29]:
print(arr1 + arr2) 
print(np.add(arr1, arr2))

[[15 10 11]
 [12  9 12]
 [14 11  7]]
[[15 10 11]
 [12  9 12]
 [14 11  7]]


In [30]:
print(np.subtract(arr1, arr2, dtype=np.int64))
print('\n','*' * 100, '\n')
print(np.multiply(arr1, arr2, dtype=np.int64))
print('\n','*' * 100, '\n')
print(np.divide(arr1, arr2))
print('\n','*' * 100, '\n')
print(np.sqrt(arr1))
print('\n','*' * 100, '\n')
print(np.exp(arr1))

[[ 3 -4  1]
 [ 2 -3  2]
 [ 2 -3  1]]

 **************************************************************************************************** 

[[54 21 30]
 [35 18 35]
 [48 28 12]]

 **************************************************************************************************** 

[[1.5        0.42857143 1.2       ]
 [1.4        0.5        1.4       ]
 [1.33333333 0.57142857 1.33333333]]

 **************************************************************************************************** 

[[3.         1.73205081 2.44948974]
 [2.64575131 1.73205081 2.64575131]
 [2.82842712 2.         2.        ]]

 **************************************************************************************************** 

[[8103.08392758   20.08553692  403.42879349]
 [1096.63315843   20.08553692 1096.63315843]
 [2980.95798704   54.59815003   54.59815003]]


## Statistical Operations

In [31]:
arrayOne = np.random.randint(0, 10, size=(3, 3))
arrayOne

array([[7, 0, 7],
       [1, 3, 6],
       [5, 3, 9]])

In [32]:
print(arrayOne.mean())

4.555555555555555


In [33]:
arrayOne.mean(axis=1)

array([4.66666667, 3.33333333, 5.66666667])

In [34]:
arrayOne.mean(axis=0)

array([4.33333333, 2.        , 7.33333333])

In [35]:
arrayOne.sum()

41

In [36]:
print(arrayOne)
np.median(arrayOne, axis=0)

[[7 0 7]
 [1 3 6]
 [5 3 9]]


array([5., 3., 7.])

In [37]:
np.median(arrayOne, axis=1)

array([7., 3., 5.])

In [38]:
#Sorting
print(arrayOne)
arrayTwo = arrayOne.copy()
print(arrayTwo)
arrayTwo.sort(axis=0)
arrayTwo

[[7 0 7]
 [1 3 6]
 [5 3 9]]
[[7 0 7]
 [1 3 6]
 [5 3 9]]


array([[1, 0, 6],
       [5, 3, 7],
       [7, 3, 9]])

In [39]:
# Find Unique Elements
print(arrayOne)
print(arrayTwo)
np.unique(arrayOne, axis=0)

[[7 0 7]
 [1 3 6]
 [5 3 9]]
[[1 0 6]
 [5 3 7]
 [7 3 9]]


array([[1, 3, 6],
       [5, 3, 9],
       [7, 0, 7]])

In [48]:
arrayOne = np.random.randint(0, 10, size=(4, 4))
arrayOne

array([[6, 9, 1, 3],
       [3, 0, 2, 6],
       [6, 6, 9, 3],
       [9, 0, 6, 1]])

In [52]:
arrayOne.reshape(2, 8)

array([[6, 9, 1, 3, 3, 0, 2, 6],
       [6, 6, 9, 3, 9, 0, 6, 1]])

In [58]:
np.arange(9, 16, 3)

array([ 9, 12, 15])

In [64]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [67]:
print("Hello World!")

Hello World!
