In [1]:
import numpy as np

In [2]:
# 1d  array
arrayOne = np.array([1, 2, 3])
type(arrayOne)

numpy.ndarray

In [3]:
# 2d array
arrayTwo = np.array([[1, 2, 3], [4, 5, 6]])
print(arrayTwo.shape)
arrayTwo

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# accessing array
arrayTwo[0][2]

3

In [5]:
zeroArray = np.zeros([2, 4, 3], dtype=np.int64)
zeroArray

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [6]:
eyeArray = np.eye(4, 4, dtype=np.int64)
eyeArray

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int64)

In [7]:
oneArray = np.ones([3, 3, 4, 2], dtype=np.int64)
oneArray

array([[[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]]], dtype=int64)

In [8]:
randArray = np.random.random([3, 4, 5])
randArray.shape

(3, 4, 5)

In [9]:
# slicing & indexing 
copyRandArray = randArray[:2 , 0:2, 1:].copy()
randArray[:2 , 0:2, 1:]

array([[[0.33529014, 0.18962312, 0.75968839, 0.53264063],
        [0.73862303, 0.37593564, 0.58042473, 0.43776442]],

       [[0.8291767 , 0.34495   , 0.32137516, 0.36311838],
        [0.26043525, 0.78462401, 0.81898632, 0.01143345]]])

In [10]:
for i in copyRandArray:
    for j in i:
        for k in j:
            print(k)

0.33529014439829874
0.189623121969975
0.7596883866823257
0.5326406330363598
0.7386230286944788
0.37593563608780833
0.5804247338927444
0.43776441953067835
0.8291767045134341
0.3449499967879124
0.32137516004100186
0.36311837571057093
0.26043525211770024
0.7846240080162123
0.8189863187270623
0.011433450795057754


In [11]:
def addition(x, y):
    print(x+y)
    
listOne = [1, 2, 3, 4, 5]
listTwo = [2, 3, 4, 5, 6]

result = map(addition, listOne, listTwo)

print(type(result))
for i in result:
    print(i)

<class 'map'>
3
None
5
None
7
None
9
None
11
None


In [12]:
# deep copy and shallow copy 
firstArray = np.array([[1, 2, 3], [2, 3, 4]])
firstArray

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
# deep copy
secondArray = firstArray.copy()
secondArray

array([[1, 2, 3],
       [2, 3, 4]])

In [14]:
firstArray[0, 1] = 3
print(secondArray)
firstArray

[[1 2 3]
 [2 3 4]]


array([[1, 3, 3],
       [2, 3, 4]])

In [15]:
thirdArray = np.copy(firstArray)
thirdArray

array([[1, 3, 3],
       [2, 3, 4]])

In [16]:
firstArray[0, 1] = 2
print(firstArray)
thirdArray

[[1 2 3]
 [2 3 4]]


array([[1, 3, 3],
       [2, 3, 4]])

In [17]:
randInt = np.random.randint(3, 10, size=(3, 3))
randInt

array([[9, 5, 3],
       [3, 6, 3],
       [9, 9, 7]])

## Boolean Indexing

In [18]:
randIntTwo = randInt.copy()
randIntTwo

array([[9, 5, 3],
       [3, 6, 3],
       [9, 9, 7]])

In [19]:
resArray = randIntTwo > 5
resArray

array([[ True, False, False],
       [False,  True, False],
       [ True,  True,  True]])

In [20]:
randIntThree = np.random.randint(3, 10, size=(3, 3))
randIntThree

array([[3, 9, 4],
       [5, 3, 3],
       [8, 5, 5]])

In [21]:
print(randIntThree)
randIntTwo

[[3 9 4]
 [5 3 3]
 [8 5 5]]


array([[9, 5, 3],
       [3, 6, 3],
       [9, 9, 7]])

In [22]:
print(randIntTwo[resArray])
print(type(resArray))
print(randIntTwo[randIntTwo > randIntThree])
print(randIntThree[randIntTwo > randIntThree])

[9 6 9 9 7]
<class 'numpy.ndarray'>
[9 6 9 9 7]
[3 3 8 5 5]


In [23]:
randIntThree

array([[3, 9, 4],
       [5, 3, 3],
       [8, 5, 5]])

In [24]:
randIntThree[randIntThree % 2 == 0] += 100

In [25]:
randIntThree

array([[  3,   9, 104],
       [  5,   3,   3],
       [108,   5,   5]])

## Datatype And Operators

In [26]:
ex1 = np.array([[1, 2, 3], [2, 3, 4]], dtype=np.int64)
print(ex1.dtype)
ex1.shape

int64


(2, 3)

In [27]:
# force float into integer using floor function
ex2 = np.array(ex1, dtype=np.float32)
print(ex2.shape)
ex2

(2, 3)


array([[1., 2., 3.],
       [2., 3., 4.]], dtype=float32)

## Arithmetic Operations

In [28]:
arr1 = np.random.randint(3, 10, size=(3, 3))
arr2 = np.random.randint(3, 10, size=(3, 3))

arr1, arr2

(array([[8, 5, 3],
        [9, 9, 6],
        [4, 8, 7]]), array([[7, 9, 9],
        [7, 8, 9],
        [8, 5, 7]]))

In [29]:
print(arr1 + arr2) 
print(np.add(arr1, arr2))

[[15 14 12]
 [16 17 15]
 [12 13 14]]
[[15 14 12]
 [16 17 15]
 [12 13 14]]


In [30]:
print(np.subtract(arr1, arr2, dtype=np.int64))
print('\n','*' * 100, '\n')
print(np.multiply(arr1, arr2, dtype=np.int64))
print('\n','*' * 100, '\n')
print(np.divide(arr1, arr2))
print('\n','*' * 100, '\n')
print(np.sqrt(arr1))
print('\n','*' * 100, '\n')
print(np.exp(arr1))

[[ 1 -4 -6]
 [ 2  1 -3]
 [-4  3  0]]

 **************************************************************************************************** 

[[56 45 27]
 [63 72 54]
 [32 40 49]]

 **************************************************************************************************** 

[[1.14285714 0.55555556 0.33333333]
 [1.28571429 1.125      0.66666667]
 [0.5        1.6        1.        ]]

 **************************************************************************************************** 

[[2.82842712 2.23606798 1.73205081]
 [3.         3.         2.44948974]
 [2.         2.82842712 2.64575131]]

 **************************************************************************************************** 

[[2980.95798704  148.4131591    20.08553692]
 [8103.08392758 8103.08392758  403.42879349]
 [  54.59815003 2980.95798704 1096.63315843]]


## Statistical Operations

In [31]:
arrayOne = np.random.randint(0, 10, size=(3, 3))
arrayOne

array([[4, 7, 7],
       [1, 8, 7],
       [9, 4, 0]])

In [32]:
print(arrayOne.mean())

5.222222222222222


In [33]:
arrayOne.mean(axis=1)

array([6.        , 5.33333333, 4.33333333])

In [34]:
arrayOne.mean(axis=0)

array([4.66666667, 6.33333333, 4.66666667])

In [35]:
arrayOne.sum()

47

In [36]:
print(arrayOne)
np.median(arrayOne, axis=0)

[[4 7 7]
 [1 8 7]
 [9 4 0]]


array([4., 7., 7.])

In [37]:
np.median(arrayOne, axis=1)

array([7., 7., 4.])

In [38]:
#Sorting
print(arrayOne)
arrayTwo = arrayOne.copy()
print(arrayTwo)
arrayTwo.sort(axis=0)
arrayTwo

[[4 7 7]
 [1 8 7]
 [9 4 0]]
[[4 7 7]
 [1 8 7]
 [9 4 0]]


array([[1, 4, 0],
       [4, 7, 7],
       [9, 8, 7]])

In [39]:
# Find Unique Elements
print(arrayOne)
print(arrayTwo)
np.unique(arrayOne, axis=0)

[[4 7 7]
 [1 8 7]
 [9 4 0]]
[[1 4 0]
 [4 7 7]
 [9 8 7]]


array([[1, 8, 7],
       [4, 7, 7],
       [9, 4, 0]])

In [40]:
arrayOne = np.random.randint(0, 10, size=(4, 4))
arrayOne

array([[3, 3, 9, 4],
       [8, 2, 7, 3],
       [6, 8, 8, 5],
       [9, 8, 3, 7]])

In [41]:
arrayOne.reshape(2, 8)

array([[3, 3, 9, 4, 8, 2, 7, 3],
       [6, 8, 8, 5, 9, 8, 3, 7]])

In [42]:
np.arange(9, 16, 3)

array([ 9, 12, 15])

In [43]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [44]:
print("Hello World!")

Hello World!


In [45]:
arrayOne = np.random.randint(0, 10, size=(1, 3)) 
print(np.median(arrayOne))
arrayOne

7.0


array([[5, 8, 7]])

In [46]:
randArray = np.random.randint(0, 100, size=(4, 4))
print(randArray)

filterArray = randArray > 20
print(filterArray)

resArray = randArray[filterArray]
print(resArray)

resArray[resArray % 2 == 0] += 100
resArray

[[58 95 31 44]
 [42 87 79 54]
 [47 37 69 15]
 [58 54 53 50]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True False]
 [ True  True  True  True]]
[58 95 31 44 42 87 79 54 47 37 69 58 54 53 50]


array([158,  95,  31, 144, 142,  87,  79, 154,  47,  37,  69, 158, 154,
        53, 150])

In [47]:
randOne = np.random.randint(0, 10, size=(2, 2))
randTwo = np.random.randint(0, 10, size=(2, 2))

In [48]:
print(randOne, "\n\n\n", randTwo)

[[3 0]
 [8 9]] 


 [[7 8]
 [2 6]]


In [49]:
np.intersect1d(randOne, randTwo)

array([8])

In [50]:
np.union1d(randOne, randTwo)

array([0, 2, 3, 6, 7, 8, 9])

## Brodcasting

In [51]:
randOne = np.random.randint(0, 10, size=(3, 3))
randOne

array([[9, 3, 8],
       [6, 0, 6],
       [4, 7, 3]])

In [52]:
randTwo = np.random.randint(0, 10, size=(1, 3))
randTwo

array([[9, 2, 9]])

In [53]:
randOne + randTwo

array([[18,  5, 17],
       [15,  2, 15],
       [13,  9, 12]])

In [54]:
randOne + randTwo.T

array([[18, 12, 17],
       [ 8,  2,  8],
       [13, 16, 12]])

In [75]:
randArray = np.random.randint(0, 2, size=(1, 10))
randArray

array([[1, 1, 0, 0, 0, 1, 0, 1, 0, 0]])

In [76]:
arrayOne = np.random.randint(0, 100, size=(1, 10))
arrayTwo = np.random.randint(0, 100, size=(1, 10))
print(arrayOne, arrayTwo)

[[89 31 80 93 94 76 66 93 99 60]] [[63 33 89 23 92 95  1 52 12 20]]


In [78]:
resArray = np.where(randArray, arrayOne, arrayTwo)

In [79]:
resArray

array([[89, 31, 89, 23, 92, 76,  1, 93, 12, 20]])

In [82]:
randArray.any()

True

In [83]:
randArray.all()

False

In [86]:
randArrayTwo = np.random.randint(1, 2, size=(1, 10))
randArrayTwo

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [87]:
randArrayTwo.all()

True